apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zcp-alertmanager-store-data
  namespace: zcp-system
  annotations:
    volume.beta.kubernetes.io/storage-class: managed-standard-retain
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: managed-standard-retain
