apiVersion: v1
kind: ConfigMap
metadata:
  name: zcp-alertmanager-store-mariadb
  namespace: zcp-system
data:
  mariadb.cnf: |
    [client]
    port            = 3306
    socket          = /var/run/mysqld/mysqld.sock
    default-character-set = utf8  #tuning

    [mysqld_safe]
    socket          = /var/run/mysqld/mysqld.sock
    nice            = 0
    skip_syslog

    [mysqld]
    #
    # * Basic Settings
    #
    user            = mysql
    pid-file        = /var/run/mysqld/mysqld.pid
    socket          = /var/run/mysqld/mysqld.sock
    port            = 3306
    basedir         = /usr
    datadir         = /var/lib/mysql
    tmpdir          = /tmp
    lc_messages_dir = /usr/share/mysql
    lc_messages     = en_US
    skip-external-locking
    bind-address            = 0.0.0.0   
    
    max_connections         = 500   #tuning
    wait_timeout            = 600   #tuning
    max_allowed_packet      = 256M  #tuning
    thread_cache_size       = 128
    sort_buffer_size        = 4M
    bulk_insert_buffer_size = 16M
    tmp_table_size          = 32M
    max_heap_table_size     = 32M

    #
    # * MyISAM
    #
    # This replaces the startup script and checks MyISAM tables if needed
    # the first time they are touched. On error, make copy and try a repair.
    myisam_recover_options = BACKUP
    key_buffer_size         = 1G    #tuning
    #open-files-limit       = 2000
    table_open_cache        = 400
    myisam_sort_buffer_size = 512M
    concurrent_insert       = 2
    read_buffer_size        = 2M
    read_rnd_buffer_size    = 1M

    #
    # * Query Cache Configuration
    #
    # Cache only tiny result sets, so we can fit more in the query cache.
    query_cache_limit               = 128K
    query_cache_size                = 1G    #tuning
    # for more write intensive setups, set to DEMAND or OFF
    #query_cache_type               = DEMAND
    #
    # * Logging and Replication
    #
    # Both location gets rotated by the cronjob.
    # Be aware that this log type is a performance killer.
    # As of 5.1 you can enable the log at runtime!
    general_log_file        = /var/log/mysql/mysql.log
    general_log             = 1
    log_error               = /var/log/mysql/error.log
    #
    # Error logging goes to syslog due to /etc/mysql/conf.d/mysqld_safe_syslog.cnf.
    #
    # we do want to know about network errors and such
    log_warnings            = 2

    #
    # Enable the slow query log to see queries with especially long duration
    #slow_query_log[={0|1}]
    slow_query_log_file     = /var/log/mysql/mariadb-slow.log
    long_query_time = 10
    #log_slow_rate_limit    = 1000
    log_slow_verbosity      = query_plan
    #log-queries-not-using-indexes
    #log_slow_admin_statements
    #
    # The following can be used as easy to replay backup logs or for replication.
    # note: if you are setting up a replication slave, see README.Debian about
    #       other settings you may need to change.
    #server-id              = 1
    #report_host            = master1
    #auto_increment_increment = 2
    #auto_increment_offset  = 1
    log_bin                 = /var/log/mysql/mariadb-bin
    log_bin_index           = /var/log/mysql/mariadb-bin.index
    # not fab for performance, but safer
    #sync_binlog            = 1
    expire_logs_days        = 10
    max_binlog_size         = 100M
    default_storage_engine  = InnoDB
    # you can't just change log file size, requires special procedure
    #innodb_log_file_size   = 50M
    innodb_log_file_size    = 256M  #tuning
    innodb_log_buffer_size  = 8M
    innodb_file_per_table   = 1
    innodb_open_files       = 400
    innodb_io_capacity      = 400
    innodb_flush_method     = O_DIRECT
    innodb_lock_wait_timeout=500
    innodb_buffer_pool_size=128MB
    connect_timeout=5
