apiVersion: v1
kind: Secret
metadata:
  name: zcp-alertmanager-store-mariadb
  namespace: zcp-system
type: Opaque
data:
  # Root password (base64): admin
  # echo -n "admin" | base64
  # echo -n "1f2d1e2e67df" | base64
  password: YWRtaW4=
