apiVersion: v1
kind: Service
metadata:
  name: zcp-alertmanager-store-mariadb
  namespace: zcp-system
  labels:
    app: zcp-alertmanager-store-mariadb
spec:
  type: ClusterIP
  ports:
  - port: 3306
    name: zcp-alertmanager-store-mariadb
    targetPort: mariadb
  selector:
    app: zcp-alertmanager-store-mariadb
